//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPacifico.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public decimal id { get; set; }
        public string descripcion { get; set; }
        public string modelo { get; set; }
        public int precio { get; set; }
        public short existencia { get; set; }
    }
}
